### ISSUE TITLE
Benchmarks crash on goleveldb

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/iavl#27]
Orphan cleanup issue. I'm not sure if VersionedTree has a problem, or if it is the benchmark....

```
$ go test -bench=Medium -v
Init Tree took 96.31 MB
goos: linux
goarch: amd64
pkg: github.com/tendermint/iavl/benchmarks
BenchmarkMedium/memdb-100000-100-16-40/query-miss-8         	  300000	      5091 ns/op
BenchmarkMedium/memdb-100000-100-16-40/query-hits-8         	  300000	      5897 ns/op
BenchmarkMedium/memdb-100000-100-16-40/update-8             	   10000	    291086 ns/op
BenchmarkMedium/memdb-100000-100-16-40/block-8              	      50	  29693712 ns/op
Init Tree took 57.69 MB
BenchmarkMedium/goleveldb-100000-100-16-40/query-miss-8     	  100000	     13341 ns/op
BenchmarkMedium/goleveldb-100000-100-16-40/query-hits-8     	  100000	     17206 ns/op
BenchmarkMedium/goleveldb-100000-100-16-40/update-8         	panic: Panicked on a Sanity Check: Orphan expires before it comes alive

goroutine 89 [running]:
github.com/tendermint/iavl/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0x7c22c0, 0x8a2180)
	/home/ethan/go/src/github.com/tendermint/iavl/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0xf3
github.com/tendermint/iavl.(*nodeDB).saveOrphan(0xc4201c00a0, 0xc42c2c4e40, 0x14, 0x20, 0x1, 0x0)
	/home/ethan/go/src/github.com/tendermint/iavl/nodedb.go:200 +0x189
github.com/tendermint/iavl.(*nodeDB).SaveOrphans(0xc4201c00a0, 0x2, 0xc42c43d050)
	/home/ethan/go/src/github.com/tendermint/iavl/nodedb.go:193 +0x14d
github.com/tendermint/iavl.(*orphaningTree).SaveVersion(0xc42c8ee560, 0x2)
	/home/ethan/go/src/github.com/tendermint/iavl/orphaning_tree.go:63 +0x8b
github.com/tendermint/iavl.(*VersionedTree).SaveVersion(0xc4201ce000, 0x2, 0x14, 0x20, 0xc42c8ee560, 0xc423c32b00, 0x10)
	/home/ethan/go/src/github.com/tendermint/iavl/versioned_tree.go:138 +0x107
github.com/tendermint/iavl/benchmarks.commitTree(0xc42019ca80, 0xc4201ce000)
	/home/ethan/go/src/github.com/tendermint/iavl/benchmarks/bench_test.go:39 +0x4f
github.com/tendermint/iavl/benchmarks.runUpdate(0xc42019ca80, 0xc4201ce000, 0x28, 0x64, 0xc42b386000, 0x186a0, 0x186a0, 0x4a1c54c2d)
	/home/ethan/go/src/github.com/tendermint/iavl/benchmarks/bench_test.go:83 +0x13e
github.com/tendermint/iavl/benchmarks.runSuite.func3(0xc42019ca80)
	/home/ethan/go/src/github.com/tendermint/iavl/benchmarks/bench_test.go:272 +0x6d
testing.(*B).runN(0xc42019ca80, 0x64)
	/usr/lib/go-1.9/src/testing/benchmark.go:141 +0xb2
testing.(*B).launch(0xc42019ca80)
	/usr/lib/go-1.9/src/testing/benchmark.go:291 +0x84
created by testing.(*B).doBench
	/usr/lib/go-1.9/src/testing/benchmark.go:260 +0x70
exit status 2
FAIL	github.com/tendermint/iavl/benchmarks	19.918s
```

**Comment by ethanfrey** [comment]
I can reproduce this also on `develop`: commit 595f3dcd5b6cd4a292e90757ae6d367fd7a6e653

`cd benchmarks/ && go test -bench=Medium`

**Comment by ethanfrey** [comment]
Seems like some crashed tests left half-finished dbs there. With help from @cloudhead I removed them and now it works...

```
$ go test -bench=Medium
Init Tree took 96.26 MB
goos: linux
goarch: amd64
pkg: github.com/tendermint/iavl/benchmarks
BenchmarkMedium/memdb-100000-100-16-40/query-miss-8         	  200000	      5265 ns/op
BenchmarkMedium/memdb-100000-100-16-40/query-hits-8         	  300000	      6180 ns/op
BenchmarkMedium/memdb-100000-100-16-40/update-8             	   10000	    283194 ns/op
BenchmarkMedium/memdb-100000-100-16-40/block-8              	      50	  29689677 ns/op
Init Tree took 46.96 MB
BenchmarkMedium/goleveldb-100000-100-16-40/query-miss-8     	  100000	     12652 ns/op
BenchmarkMedium/goleveldb-100000-100-16-40/query-hits-8     	  100000	     16212 ns/op
BenchmarkMedium/goleveldb-100000-100-16-40/update-8         	   10000	    330389 ns/op
BenchmarkMedium/goleveldb-100000-100-16-40/block-8          	      50	  38318145 ns/op
Init Tree took 38.89 MB
BenchmarkMedium/leveldb-100000-100-16-40/query-miss-8       	  100000	     12147 ns/op
BenchmarkMedium/leveldb-100000-100-16-40/query-hits-8       	  100000	     15993 ns/op
BenchmarkMedium/leveldb-100000-100-16-40/update-8           	   10000	    336612 ns/op
BenchmarkMedium/leveldb-100000-100-16-40/block-8            	      30	  33432249 ns/op
PASS
ok  	github.com/tendermint/iavl/benchmarks	32.400s
```
